sudo: required

services:
  - docker

language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"

before_install:
  - docker pull lab11/docker-influxdb:0.13-ci
  - docker run -d -p 8083:8083 -p 8086:8086 -p 8085:8085 -p 8084:8084 -p 9085:9085 -p 9084:9084 --expose 8090 --expose 8099 lab11/docker-influxdb:0.13-ci

script:
  - npm run travis-test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage
