name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prettier
        uses: creyD/prettier_action@v3.0
        with:
          prettier_options: --write **/*.{tsx,ts,md}
          commit_message: "style: prettier code"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-browser:
    name: "Testing Browser"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install depencencies
        run: npm ci

      - name: Run InfluxDB
        run: docker run -d -p 8083:8083 -p 8086:8086 influxdb

      - name: Run tests on Sauce
        run: npm run test:sauce

  test-node:
    name: "Testing on Node.js v${{matrix.node}}"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["10", "12", "14", "15"]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install depencencies
        run: npm ci

      - name: Run InfluxDB
        run: docker run -d -p 8083:8083 -p 8086:8086 influxdb

      - name: Run tests
        run: npm run test
